# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'allocateEnergy.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGraphicsView, QLabel,
    QMainWindow, QPushButton, QSizePolicy, QWidget)
import resource.resource3_rc

class Ui_allocateEnergy(object):
    def setupUi(self, allocateEnergy):
        if not allocateEnergy.objectName():
            allocateEnergy.setObjectName(u"allocateEnergy")
        allocateEnergy.resize(1280, 720)
        allocateEnergy.setStyleSheet(u"#centralwidget{border-image: url(:/image/resource/Strength_assign/p0424_l.png);}")
        self.centralwidget = QWidget(allocateEnergy)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(230, 40, 991, 631))
        self.label.setStyleSheet(u"border-image: url(:/image/resource/Strength_assign/02_brown.png);")
        self.pushButton_exit = QPushButton(self.centralwidget)
        self.pushButton_exit.setObjectName(u"pushButton_exit")
        self.pushButton_exit.setGeometry(QRect(1120, 680, 100, 35))
        self.pushButton_exit.setStyleSheet(u"#pushButton_exit{\n"
"	border-image: url(:/image/resource/exit_button2.png);\n"
"	}\n"
"#pushButton_exit:hover{\n"
"	\n"
"	border-image: url(:/image/resource/exit_hover.png);\n"
"}")
        self.pushButton_save = QPushButton(self.centralwidget)
        self.pushButton_save.setObjectName(u"pushButton_save")
        self.pushButton_save.setGeometry(QRect(1000, 680, 100, 35))
        self.pushButton_save.setStyleSheet(u"#pushButton_save{\n"
"	\n"
"	border-image: url(:/image/resource/save_button2.png);\n"
"	}\n"
"#pushButton_save:hover{\n"
"	\n"
"	border-image: url(:/image/resource/save_hover.png);\n"
"	}")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(290, 80, 541, 551))
        self.label_2.setStyleSheet(u"#label_2{border-image: url(:/image/resource/Strength_assign/paper2_yellow_l.png);}")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(850, 90, 311, 531))
        self.label_3.setStyleSheet(u"border-image: url(:/image/resource/Strength_assign/label2_l.png);")
        self.pushButton_next = QPushButton(self.centralwidget)
        self.pushButton_next.setObjectName(u"pushButton_next")
        self.pushButton_next.setGeometry(QRect(990, 530, 130, 41))
        font = QFont()
        font.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font.setPointSize(13)
        font.setBold(False)
        self.pushButton_next.setFont(font)
        self.pushButton_next.setStyleSheet(u"#pushButton_next{\n"
"border-image: url(:/image/resource/Strength_assign/002_07.png);\n"
"padding:10px;\n"
"}\n"
"#pushButton_next:hover{\n"
"	border-image: url(:/image/resource/Strength_assign/002_07_hover.png);}\n"
"#pushButton_next:pressed{\n"
"	border-image: url(:/image/resource/Strength_assign/002_07_click.png);}")
        self.label_optionalMission = QLabel(self.centralwidget)
        self.label_optionalMission.setObjectName(u"label_optionalMission")
        self.label_optionalMission.setGeometry(QRect(300, 90, 431, 31))
        font1 = QFont()
        font1.setFamilies([u"\u5343\u56fe\u7b14\u950b\u624b\u5199\u4f53"])
        font1.setPointSize(17)
        font1.setBold(True)
        self.label_optionalMission.setFont(font1)
        self.label_mission2 = QLabel(self.centralwidget)
        self.label_mission2.setObjectName(u"label_mission2")
        self.label_mission2.setGeometry(QRect(310, 140, 131, 41))
        self.label_mission2.setFont(font1)
        self.label_mission3 = QLabel(self.centralwidget)
        self.label_mission3.setObjectName(u"label_mission3")
        self.label_mission3.setGeometry(QRect(310, 170, 131, 41))
        self.label_mission3.setFont(font1)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 200, 161, 91))
        font2 = QFont()
        font2.setPointSize(17)
        self.label_5.setFont(font2)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignTop)
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(30, 20, 161, 161))
        self.graphicsView.setStyleSheet(u"border-image: url(:/image/resource/Strength_assign/boy_normal_-removebg-preview.png);\n"
"background-color:grey;")
        self.label_energy = QLabel(self.centralwidget)
        self.label_energy.setObjectName(u"label_energy")
        self.label_energy.setGeometry(QRect(30, 250, 171, 51))
        font3 = QFont()
        font3.setPointSize(17)
        font3.setBold(True)
        self.label_energy.setFont(font3)
        self.label_money = QLabel(self.centralwidget)
        self.label_money.setObjectName(u"label_money")
        self.label_money.setGeometry(QRect(30, 360, 171, 51))
        self.label_money.setFont(font3)
        self.label_moreEvents = QLabel(self.centralwidget)
        self.label_moreEvents.setObjectName(u"label_moreEvents")
        self.label_moreEvents.setGeometry(QRect(360, 529, 411, 31))
        self.label_moreEvents.setFont(font1)
        self.label_moreEvents.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_mission1 = QLabel(self.centralwidget)
        self.label_mission1.setObjectName(u"label_mission1")
        self.label_mission1.setGeometry(QRect(310, 120, 131, 31))
        self.label_mission1.setFont(font1)
        self.label_mission4 = QLabel(self.centralwidget)
        self.label_mission4.setObjectName(u"label_mission4")
        self.label_mission4.setEnabled(True)
        self.label_mission4.setGeometry(QRect(310, 200, 131, 31))
        self.label_mission4.setFont(font1)
        self.label_mission5 = QLabel(self.centralwidget)
        self.label_mission5.setObjectName(u"label_mission5")
        self.label_mission5.setGeometry(QRect(310, 220, 131, 51))
        self.label_mission5.setFont(font1)
        self.label_mission6 = QLabel(self.centralwidget)
        self.label_mission6.setObjectName(u"label_mission6")
        self.label_mission6.setGeometry(QRect(310, 250, 141, 41))
        self.label_mission6.setFont(font1)
        self.label_mission7 = QLabel(self.centralwidget)
        self.label_mission7.setObjectName(u"label_mission7")
        self.label_mission7.setGeometry(QRect(310, 280, 141, 41))
        font4 = QFont()
        font4.setFamilies([u"\u5343\u56fe\u7b14\u950b\u624b\u5199\u4f53"])
        font4.setPointSize(17)
        self.label_mission7.setFont(font4)
        self.label_mission8 = QLabel(self.centralwidget)
        self.label_mission8.setObjectName(u"label_mission8")
        self.label_mission8.setGeometry(QRect(310, 310, 141, 31))
        self.label_mission8.setFont(font1)
        self.label_mission9 = QLabel(self.centralwidget)
        self.label_mission9.setObjectName(u"label_mission9")
        self.label_mission9.setGeometry(QRect(310, 335, 141, 41))
        self.label_mission9.setFont(font1)
        self.label_mission10 = QLabel(self.centralwidget)
        self.label_mission10.setObjectName(u"label_mission10")
        self.label_mission10.setGeometry(QRect(310, 365, 141, 41))
        self.label_mission10.setFont(font1)
        self.pushButton_minus5 = QPushButton(self.centralwidget)
        self.pushButton_minus5.setObjectName(u"pushButton_minus5")
        self.pushButton_minus5.setGeometry(QRect(890, 440, 40, 40))
        font5 = QFont()
        font5.setPointSize(48)
        self.pushButton_minus5.setFont(font5)
        self.pushButton_minus5.setStyleSheet(u"border-image: url(:/image/resource/\u51cf\u53f7.png);\n"
"")
        self.pushButton_plus5 = QPushButton(self.centralwidget)
        self.pushButton_plus5.setObjectName(u"pushButton_plus5")
        self.pushButton_plus5.setGeometry(QRect(1080, 440, 40, 40))
        self.pushButton_plus5.setStyleSheet(u"\n"
"	border-image: url(:/image/resource/\u52a0\u53f7.png);")
        self.pushButton_minus4 = QPushButton(self.centralwidget)
        self.pushButton_minus4.setObjectName(u"pushButton_minus4")
        self.pushButton_minus4.setGeometry(QRect(890, 370, 40, 40))
        self.pushButton_minus4.setFont(font5)
        self.pushButton_minus4.setStyleSheet(u"border-image: url(:/image/resource/\u51cf\u53f7.png);\n"
"")
        self.pushButton_plus4 = QPushButton(self.centralwidget)
        self.pushButton_plus4.setObjectName(u"pushButton_plus4")
        self.pushButton_plus4.setGeometry(QRect(1080, 370, 40, 40))
        self.pushButton_plus4.setStyleSheet(u"\n"
"	border-image: url(:/image/resource/\u52a0\u53f7.png);")
        self.pushButton_minus3 = QPushButton(self.centralwidget)
        self.pushButton_minus3.setObjectName(u"pushButton_minus3")
        self.pushButton_minus3.setGeometry(QRect(890, 300, 40, 40))
        self.pushButton_minus3.setFont(font5)
        self.pushButton_minus3.setStyleSheet(u"border-image: url(:/image/resource/\u51cf\u53f7.png);\n"
"")
        self.pushButton_plus3 = QPushButton(self.centralwidget)
        self.pushButton_plus3.setObjectName(u"pushButton_plus3")
        self.pushButton_plus3.setGeometry(QRect(1080, 300, 40, 40))
        self.pushButton_plus3.setFont(font5)
        self.pushButton_plus3.setStyleSheet(u"border-image: url(:/image/resource/\u52a0\u53f7.png);\n"
"")
        self.pushButton_plus2 = QPushButton(self.centralwidget)
        self.pushButton_plus2.setObjectName(u"pushButton_plus2")
        self.pushButton_plus2.setGeometry(QRect(1080, 230, 40, 40))
        self.pushButton_plus2.setFont(font5)
        self.pushButton_plus2.setStyleSheet(u"border-image: url(:/image/resource/\u52a0\u53f7.png);\n"
"")
        self.pushButton_minus2 = QPushButton(self.centralwidget)
        self.pushButton_minus2.setObjectName(u"pushButton_minus2")
        self.pushButton_minus2.setGeometry(QRect(890, 230, 40, 40))
        self.pushButton_minus2.setFont(font5)
        self.pushButton_minus2.setStyleSheet(u"border-image: url(:/image/resource/\u51cf\u53f7.png);\n"
"")
        self.pushButton_plus1 = QPushButton(self.centralwidget)
        self.pushButton_plus1.setObjectName(u"pushButton_plus1")
        self.pushButton_plus1.setGeometry(QRect(1080, 170, 40, 40))
        self.pushButton_plus1.setFont(font5)
        self.pushButton_plus1.setStyleSheet(u"border-image: url(:/image/resource/\u52a0\u53f7.png);\n"
"\n"
"")
        self.pushButton_minus1 = QPushButton(self.centralwidget)
        self.pushButton_minus1.setObjectName(u"pushButton_minus1")
        self.pushButton_minus1.setGeometry(QRect(890, 170, 40, 40))
        font6 = QFont()
        font6.setPointSize(51)
        self.pushButton_minus1.setFont(font6)
        self.pushButton_minus1.setStyleSheet(u"border-image: url(:/image/resource/\u51cf\u53f7.png);\n"
"")
        self.label_mission1_listed = QLabel(self.centralwidget)
        self.label_mission1_listed.setObjectName(u"label_mission1_listed")
        self.label_mission1_listed.setGeometry(QRect(930, 160, 151, 61))
        font7 = QFont()
        font7.setFamilies([u"\u5343\u56fe\u9a6c\u514b\u624b\u5199\u4f53"])
        font7.setPointSize(16)
        font7.setBold(True)
        self.label_mission1_listed.setFont(font7)
        self.label_mission1_listed.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_mission2_listed = QLabel(self.centralwidget)
        self.label_mission2_listed.setObjectName(u"label_mission2_listed")
        self.label_mission2_listed.setGeometry(QRect(930, 220, 151, 61))
        self.label_mission2_listed.setFont(font7)
        self.label_mission2_listed.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_mission3_listed = QLabel(self.centralwidget)
        self.label_mission3_listed.setObjectName(u"label_mission3_listed")
        self.label_mission3_listed.setGeometry(QRect(930, 290, 151, 61))
        self.label_mission3_listed.setFont(font7)
        self.label_mission3_listed.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_mission4_listed = QLabel(self.centralwidget)
        self.label_mission4_listed.setObjectName(u"label_mission4_listed")
        self.label_mission4_listed.setGeometry(QRect(930, 360, 151, 61))
        self.label_mission4_listed.setFont(font7)
        self.label_mission4_listed.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_mission5_listed = QLabel(self.centralwidget)
        self.label_mission5_listed.setObjectName(u"label_mission5_listed")
        self.label_mission5_listed.setGeometry(QRect(930, 430, 151, 61))
        self.label_mission5_listed.setFont(font7)
        self.label_mission5_listed.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.pushButton_previousPage = QPushButton(self.centralwidget)
        self.pushButton_previousPage.setObjectName(u"pushButton_previousPage")
        self.pushButton_previousPage.setGeometry(QRect(920, 130, 41, 41))
        self.pushButton_previousPage.setStyleSheet(u"border-image: url(:/image/resource/\u5de6\u7bad\u5934.png);")
        self.pushButton_nextPage = QPushButton(self.centralwidget)
        self.pushButton_nextPage.setObjectName(u"pushButton_nextPage")
        self.pushButton_nextPage.setGeometry(QRect(1050, 130, 41, 41))
        self.pushButton_nextPage.setStyleSheet(u"border-image: url(:/image/resource/\u53f3\u7bad\u5934.png);")
        self.label_energy_value = QLabel(self.centralwidget)
        self.label_energy_value.setObjectName(u"label_energy_value")
        self.label_energy_value.setGeometry(QRect(50, 310, 131, 41))
        font8 = QFont()
        font8.setPointSize(19)
        font8.setBold(True)
        self.label_energy_value.setFont(font8)
        self.label_money_value = QLabel(self.centralwidget)
        self.label_money_value.setObjectName(u"label_money_value")
        self.label_money_value.setGeometry(QRect(50, 400, 151, 61))
        self.label_money_value.setFont(font8)
        self.frame_modal = QFrame(self.centralwidget)
        self.frame_modal.setObjectName(u"frame_modal")
        self.frame_modal.setGeometry(QRect(10, 160, 1111, 400))
        self.frame_modal.setStyleSheet(u"#frame_modal{border-image: url(:/image/resource/\u5f39\u7a97.png);}")
        self.frame_modal.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_modal.setFrameShadow(QFrame.Shadow.Raised)
        self.label_content = QLabel(self.frame_modal)
        self.label_content.setObjectName(u"label_content")
        self.label_content.setGeometry(QRect(450, 40, 651, 121))
        font9 = QFont()
        font9.setPointSize(20)
        font9.setBold(False)
        self.label_content.setFont(font9)
        self.label_content.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.pushButton_yes = QPushButton(self.frame_modal)
        self.pushButton_yes.setObjectName(u"pushButton_yes")
        self.pushButton_yes.setGeometry(QRect(590, 290, 74, 77))
        font10 = QFont()
        font10.setPointSize(23)
        self.pushButton_yes.setFont(font10)
        self.pushButton_yes.setStyleSheet(u"border-image: url(:/image/resource/004_02.png);")
        self.pushButton_no = QPushButton(self.frame_modal)
        self.pushButton_no.setObjectName(u"pushButton_no")
        self.pushButton_no.setGeometry(QRect(840, 290, 74, 77))
        self.pushButton_no.setFont(font10)
        self.pushButton_no.setStyleSheet(u"border-image: url(:/image/resource/004_07.png);")
        self.frame_selectArea = QFrame(self.centralwidget)
        self.frame_selectArea.setObjectName(u"frame_selectArea")
        self.frame_selectArea.setGeometry(QRect(310, 120, 311, 351))
        self.frame_selectArea.setStyleSheet(u"background-color: transparent;\n"
"border:0px;")
        self.frame_selectArea.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_selectArea.setFrameShadow(QFrame.Shadow.Raised)
        allocateEnergy.setCentralWidget(self.centralwidget)

        self.retranslateUi(allocateEnergy)

        QMetaObject.connectSlotsByName(allocateEnergy)
    # setupUi

    def retranslateUi(self, allocateEnergy):
        allocateEnergy.setWindowTitle(QCoreApplication.translate("allocateEnergy", u"MainWindow", None))
        self.label.setText("")
        self.pushButton_exit.setText("")
        self.pushButton_save.setText("")
        self.label_2.setText("")
        self.label_3.setText("")
        self.pushButton_next.setText(QCoreApplication.translate("allocateEnergy", u"\u5f00\u59cb\u65b0\u7684\u4e00\u5468", None))
        self.label_optionalMission.setText(QCoreApplication.translate("allocateEnergy", u"\u53ef\u9009\u9879\u76ee\uff1a", None))
        self.label_mission2.setText(QCoreApplication.translate("allocateEnergy", u"2.", None))
        self.label_mission3.setText(QCoreApplication.translate("allocateEnergy", u"3.", None))
        self.label_5.setText(QCoreApplication.translate("allocateEnergy", u"Your name", None))
        self.label_energy.setText(QCoreApplication.translate("allocateEnergy", u"\u7cbe\u529b\u503c\uff1a", None))
        self.label_money.setText(QCoreApplication.translate("allocateEnergy", u"\u91d1\u94b1\uff1a", None))
        self.label_moreEvents.setText(QCoreApplication.translate("allocateEnergy", u"\u66f4\u591a\u6d3b\u52a8\uff0c\u8bf7\u95ef\u5173\u89e3\u9501.........", None))
        self.label_mission1.setText(QCoreApplication.translate("allocateEnergy", u"1.\u5b66\u4e60", None))
        self.label_mission4.setText(QCoreApplication.translate("allocateEnergy", u"4.", None))
        self.label_mission5.setText(QCoreApplication.translate("allocateEnergy", u"5.", None))
        self.label_mission6.setText(QCoreApplication.translate("allocateEnergy", u"6.", None))
        self.label_mission7.setText(QCoreApplication.translate("allocateEnergy", u"7.", None))
        self.label_mission8.setText(QCoreApplication.translate("allocateEnergy", u"8.", None))
        self.label_mission9.setText(QCoreApplication.translate("allocateEnergy", u"9.", None))
        self.label_mission10.setText(QCoreApplication.translate("allocateEnergy", u"10.", None))
        self.pushButton_minus5.setText("")
        self.pushButton_plus5.setText("")
        self.pushButton_minus4.setText("")
        self.pushButton_plus4.setText("")
        self.pushButton_minus3.setText("")
        self.pushButton_plus3.setText("")
        self.pushButton_plus2.setText("")
        self.pushButton_minus2.setText("")
        self.pushButton_plus1.setText("")
        self.pushButton_minus1.setText("")
        self.label_mission1_listed.setText(QCoreApplication.translate("allocateEnergy", u"\u793e\u56e2\u6d3b\u52a8  1000", None))
        self.label_mission2_listed.setText(QCoreApplication.translate("allocateEnergy", u"\u793e\u56e2\u6d3b\u52a8  1000", None))
        self.label_mission3_listed.setText(QCoreApplication.translate("allocateEnergy", u"\u793e\u56e2\u6d3b\u52a8  1000", None))
        self.label_mission4_listed.setText(QCoreApplication.translate("allocateEnergy", u"\u793e\u56e2\u6d3b\u52a8  1000", None))
        self.label_mission5_listed.setText(QCoreApplication.translate("allocateEnergy", u"\u793e\u56e2\u6d3b\u52a8  1000", None))
        self.pushButton_previousPage.setText("")
        self.pushButton_nextPage.setText("")
        self.label_energy_value.setText(QCoreApplication.translate("allocateEnergy", u"100", None))
        self.label_money_value.setText(QCoreApplication.translate("allocateEnergy", u"10000", None))
        self.label_content.setText(QCoreApplication.translate("allocateEnergy", u"\u5b66\u6821\u5c06\u4e3e\u529e\u8fce\u65b0\u665a\u4f1a\uff0c\u4f60\u662f\u5426\u9009\u62e9\u53c2\u52a0\uff1f", None))
        self.pushButton_yes.setText(QCoreApplication.translate("allocateEnergy", u"\u662f", None))
        self.pushButton_no.setText(QCoreApplication.translate("allocateEnergy", u"\u5426", None))
    # retranslateUi

