# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'strength_assignment.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGraphicsView, QLabel,
    QMainWindow, QPushButton, QSizePolicy, QWidget)
import resource.resource3_rc

class Ui_strength_assignment(object):
    def setupUi(self, strength_assignment):
        if not strength_assignment.objectName():
            strength_assignment.setObjectName(u"strength_assignment")
        strength_assignment.resize(1280, 720)
        strength_assignment.setStyleSheet(u"#centralwidget{border-image: url(:/image/resource/Strength_assign/p0424_l.png);}")
        self.centralwidget = QWidget(strength_assignment)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(230, 40, 991, 631))
        self.label.setStyleSheet(u"border-image: url(:/image/resource/Strength_assign/02_brown.png);")
        self.exit_button = QPushButton(self.centralwidget)
        self.exit_button.setObjectName(u"exit_button")
        self.exit_button.setGeometry(QRect(1120, 680, 100, 35))
        self.exit_button.setStyleSheet(u"#exit_button{\n"
"	border-image: url(:/image/resource/exit_button2.png);\n"
"	}\n"
"#exit_button:hover{\n"
"	\n"
"	border-image: url(:/image/resource/exit_hover.png);\n"
"}")
        self.save_button = QPushButton(self.centralwidget)
        self.save_button.setObjectName(u"save_button")
        self.save_button.setGeometry(QRect(1000, 680, 100, 35))
        self.save_button.setStyleSheet(u"#save_button{\n"
"	\n"
"	border-image: url(:/image/resource/save_button2.png);\n"
"	}\n"
"#save_button:hover{\n"
"	\n"
"	border-image: url(:/image/resource/save_hover.png);\n"
"	}")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(290, 80, 541, 551))
        self.label_2.setStyleSheet(u"#label_2{border-image: url(:/image/resource/Strength_assign/paper2_yellow_l.png);}")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(850, 90, 311, 531))
        self.label_3.setStyleSheet(u"border-image: url(:/image/resource/Strength_assign/label2_l.png);")
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(990, 530, 130, 41))
        font = QFont()
        font.setFamilies([u"\u5fae\u8f6f\u96c5\u9ed1"])
        font.setPointSize(13)
        font.setBold(False)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet(u"#pushButton_5{\n"
"border-image: url(:/image/resource/Strength_assign/002_07.png);\n"
"padding:10px;\n"
"}\n"
"#pushButton_5:hover{\n"
"	border-image: url(:/image/resource/Strength_assign/002_07_hover.png);}\n"
"#pushButton_5:pressed{\n"
"	border-image: url(:/image/resource/Strength_assign/002_07_click.png);}")
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(300, 90, 431, 31))
        font1 = QFont()
        font1.setFamilies([u"\u5343\u56fe\u7b14\u950b\u624b\u5199\u4f53"])
        font1.setPointSize(17)
        font1.setBold(True)
        self.label_6.setFont(font1)
        self.mission_2 = QLabel(self.centralwidget)
        self.mission_2.setObjectName(u"mission_2")
        self.mission_2.setGeometry(QRect(310, 140, 131, 41))
        self.mission_2.setFont(font1)
        self.mission_3 = QLabel(self.centralwidget)
        self.mission_3.setObjectName(u"mission_3")
        self.mission_3.setGeometry(QRect(310, 170, 131, 41))
        self.mission_3.setFont(font1)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 200, 161, 91))
        font2 = QFont()
        font2.setPointSize(17)
        self.label_5.setFont(font2)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignTop)
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(30, 20, 161, 161))
        self.graphicsView.setStyleSheet(u"border-image: url(:/image/resource/Strength_assign/boy_normal_-removebg-preview.png);\n"
"background-color:grey;")
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 250, 171, 51))
        font3 = QFont()
        font3.setPointSize(17)
        font3.setBold(True)
        self.label_7.setFont(font3)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 360, 171, 51))
        self.label_8.setFont(font3)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(360, 529, 411, 31))
        self.label_9.setFont(font1)
        self.label_9.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.misson_1 = QLabel(self.centralwidget)
        self.misson_1.setObjectName(u"misson_1")
        self.misson_1.setGeometry(QRect(310, 120, 131, 31))
        self.misson_1.setFont(font1)
        self.mission_4 = QLabel(self.centralwidget)
        self.mission_4.setObjectName(u"mission_4")
        self.mission_4.setEnabled(True)
        self.mission_4.setGeometry(QRect(310, 200, 131, 31))
        self.mission_4.setFont(font1)
        self.mission_5 = QLabel(self.centralwidget)
        self.mission_5.setObjectName(u"mission_5")
        self.mission_5.setGeometry(QRect(310, 220, 131, 51))
        self.mission_5.setFont(font1)
        self.mission_6 = QLabel(self.centralwidget)
        self.mission_6.setObjectName(u"mission_6")
        self.mission_6.setGeometry(QRect(310, 250, 141, 41))
        self.mission_6.setFont(font1)
        self.mission_7 = QLabel(self.centralwidget)
        self.mission_7.setObjectName(u"mission_7")
        self.mission_7.setGeometry(QRect(310, 280, 141, 41))
        font4 = QFont()
        font4.setFamilies([u"\u5343\u56fe\u7b14\u950b\u624b\u5199\u4f53"])
        font4.setPointSize(17)
        self.mission_7.setFont(font4)
        self.mission_8 = QLabel(self.centralwidget)
        self.mission_8.setObjectName(u"mission_8")
        self.mission_8.setGeometry(QRect(310, 310, 141, 31))
        self.mission_8.setFont(font1)
        self.mission_9 = QLabel(self.centralwidget)
        self.mission_9.setObjectName(u"mission_9")
        self.mission_9.setGeometry(QRect(310, 335, 141, 41))
        self.mission_9.setFont(font1)
        self.mission_10 = QLabel(self.centralwidget)
        self.mission_10.setObjectName(u"mission_10")
        self.mission_10.setGeometry(QRect(310, 365, 141, 41))
        self.mission_10.setFont(font1)
        self.minus5 = QPushButton(self.centralwidget)
        self.minus5.setObjectName(u"minus5")
        self.minus5.setGeometry(QRect(890, 440, 40, 40))
        font5 = QFont()
        font5.setPointSize(48)
        self.minus5.setFont(font5)
        self.minus5.setStyleSheet(u"border-image: url(:/image/resource/\u51cf\u53f7.png);\n"
"")
        self.plus5 = QPushButton(self.centralwidget)
        self.plus5.setObjectName(u"plus5")
        self.plus5.setGeometry(QRect(1080, 440, 40, 40))
        self.plus5.setStyleSheet(u"\n"
"	border-image: url(:/image/resource/\u52a0\u53f7.png);")
        self.minus4 = QPushButton(self.centralwidget)
        self.minus4.setObjectName(u"minus4")
        self.minus4.setGeometry(QRect(890, 370, 40, 40))
        self.minus4.setFont(font5)
        self.minus4.setStyleSheet(u"border-image: url(:/image/resource/\u51cf\u53f7.png);\n"
"")
        self.plus4 = QPushButton(self.centralwidget)
        self.plus4.setObjectName(u"plus4")
        self.plus4.setGeometry(QRect(1080, 370, 40, 40))
        self.plus4.setStyleSheet(u"\n"
"	border-image: url(:/image/resource/\u52a0\u53f7.png);")
        self.minus3 = QPushButton(self.centralwidget)
        self.minus3.setObjectName(u"minus3")
        self.minus3.setGeometry(QRect(890, 300, 40, 40))
        self.minus3.setFont(font5)
        self.minus3.setStyleSheet(u"border-image: url(:/image/resource/\u51cf\u53f7.png);\n"
"")
        self.plus3 = QPushButton(self.centralwidget)
        self.plus3.setObjectName(u"plus3")
        self.plus3.setGeometry(QRect(1080, 300, 40, 40))
        self.plus3.setFont(font5)
        self.plus3.setStyleSheet(u"border-image: url(:/image/resource/\u52a0\u53f7.png);\n"
"")
        self.plus2 = QPushButton(self.centralwidget)
        self.plus2.setObjectName(u"plus2")
        self.plus2.setGeometry(QRect(1080, 230, 40, 40))
        self.plus2.setFont(font5)
        self.plus2.setStyleSheet(u"border-image: url(:/image/resource/\u52a0\u53f7.png);\n"
"")
        self.minus2 = QPushButton(self.centralwidget)
        self.minus2.setObjectName(u"minus2")
        self.minus2.setGeometry(QRect(890, 230, 40, 40))
        self.minus2.setFont(font5)
        self.minus2.setStyleSheet(u"border-image: url(:/image/resource/\u51cf\u53f7.png);\n"
"")
        self.plus1 = QPushButton(self.centralwidget)
        self.plus1.setObjectName(u"plus1")
        self.plus1.setGeometry(QRect(1080, 170, 40, 40))
        self.plus1.setFont(font5)
        self.plus1.setStyleSheet(u"border-image: url(:/image/resource/\u52a0\u53f7.png);\n"
"\n"
"")
        self.minus1 = QPushButton(self.centralwidget)
        self.minus1.setObjectName(u"minus1")
        self.minus1.setGeometry(QRect(890, 170, 40, 40))
        font6 = QFont()
        font6.setPointSize(51)
        self.minus1.setFont(font6)
        self.minus1.setStyleSheet(u"border-image: url(:/image/resource/\u51cf\u53f7.png);\n"
"")
        self.mission1_show = QLabel(self.centralwidget)
        self.mission1_show.setObjectName(u"mission1_show")
        self.mission1_show.setGeometry(QRect(930, 160, 151, 61))
        font7 = QFont()
        font7.setFamilies([u"\u5343\u56fe\u9a6c\u514b\u624b\u5199\u4f53"])
        font7.setPointSize(16)
        font7.setBold(True)
        self.mission1_show.setFont(font7)
        self.mission1_show.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.mission2_show = QLabel(self.centralwidget)
        self.mission2_show.setObjectName(u"mission2_show")
        self.mission2_show.setGeometry(QRect(930, 220, 151, 61))
        self.mission2_show.setFont(font7)
        self.mission2_show.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.mission3_show = QLabel(self.centralwidget)
        self.mission3_show.setObjectName(u"mission3_show")
        self.mission3_show.setGeometry(QRect(930, 290, 151, 61))
        self.mission3_show.setFont(font7)
        self.mission3_show.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.mission4_show = QLabel(self.centralwidget)
        self.mission4_show.setObjectName(u"mission4_show")
        self.mission4_show.setGeometry(QRect(930, 360, 151, 61))
        self.mission4_show.setFont(font7)
        self.mission4_show.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.mission5_show = QLabel(self.centralwidget)
        self.mission5_show.setObjectName(u"mission5_show")
        self.mission5_show.setGeometry(QRect(930, 430, 151, 61))
        self.mission5_show.setFont(font7)
        self.mission5_show.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.left_button = QPushButton(self.centralwidget)
        self.left_button.setObjectName(u"left_button")
        self.left_button.setGeometry(QRect(920, 130, 41, 41))
        self.left_button.setStyleSheet(u"border-image: url(:/image/resource/\u5de6\u7bad\u5934.png);")
        self.right_button = QPushButton(self.centralwidget)
        self.right_button.setObjectName(u"right_button")
        self.right_button.setGeometry(QRect(1050, 130, 41, 41))
        self.right_button.setStyleSheet(u"border-image: url(:/image/resource/\u53f3\u7bad\u5934.png);")
        self.total_strength = QLabel(self.centralwidget)
        self.total_strength.setObjectName(u"total_strength")
        self.total_strength.setGeometry(QRect(50, 310, 131, 41))
        font8 = QFont()
        font8.setPointSize(19)
        font8.setBold(True)
        self.total_strength.setFont(font8)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(50, 400, 151, 61))
        self.label_14.setFont(font8)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 160, 1111, 400))
        self.frame.setStyleSheet(u"#frame{border-image: url(:/image/resource/\u5f39\u7a97.png);}")
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.shifo_label = QLabel(self.frame)
        self.shifo_label.setObjectName(u"shifo_label")
        self.shifo_label.setGeometry(QRect(450, 40, 651, 121))
        font9 = QFont()
        font9.setPointSize(20)
        font9.setBold(False)
        self.shifo_label.setFont(font9)
        self.shifo_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.true_button = QPushButton(self.frame)
        self.true_button.setObjectName(u"true_button")
        self.true_button.setGeometry(QRect(590, 290, 74, 77))
        font10 = QFont()
        font10.setPointSize(23)
        self.true_button.setFont(font10)
        self.true_button.setStyleSheet(u"border-image: url(:/image/resource/004_02.png);")
        self.false_button = QPushButton(self.frame)
        self.false_button.setObjectName(u"false_button")
        self.false_button.setGeometry(QRect(840, 290, 74, 77))
        self.false_button.setFont(font10)
        self.false_button.setStyleSheet(u"border-image: url(:/image/resource/004_07.png);")
        strength_assignment.setCentralWidget(self.centralwidget)

        self.retranslateUi(strength_assignment)

        QMetaObject.connectSlotsByName(strength_assignment)
    # setupUi

    def retranslateUi(self, strength_assignment):
        strength_assignment.setWindowTitle(QCoreApplication.translate("strength_assignment", u"MainWindow", None))
        self.label.setText("")
        self.exit_button.setText("")
        self.save_button.setText("")
        self.label_2.setText("")
        self.label_3.setText("")
        self.pushButton_5.setText(QCoreApplication.translate("strength_assignment", u"\u5f00\u59cb\u65b0\u7684\u4e00\u5468", None))
        self.label_6.setText(QCoreApplication.translate("strength_assignment", u"\u53ef\u9009\u9879\u76ee\uff1a", None))
        self.mission_2.setText(QCoreApplication.translate("strength_assignment", u"2.", None))
        self.mission_3.setText(QCoreApplication.translate("strength_assignment", u"3.", None))
        self.label_5.setText(QCoreApplication.translate("strength_assignment", u"Your name", None))
        self.label_7.setText(QCoreApplication.translate("strength_assignment", u"\u7cbe\u529b\u503c\uff1a", None))
        self.label_8.setText(QCoreApplication.translate("strength_assignment", u"\u91d1\u94b1\uff1a", None))
        self.label_9.setText(QCoreApplication.translate("strength_assignment", u"\u66f4\u591a\u6d3b\u52a8\uff0c\u8bf7\u95ef\u5173\u89e3\u9501.........", None))
        self.misson_1.setText(QCoreApplication.translate("strength_assignment", u"1.\u5b66\u4e60", None))
        self.mission_4.setText(QCoreApplication.translate("strength_assignment", u"4.", None))
        self.mission_5.setText(QCoreApplication.translate("strength_assignment", u"5.", None))
        self.mission_6.setText(QCoreApplication.translate("strength_assignment", u"6.", None))
        self.mission_7.setText(QCoreApplication.translate("strength_assignment", u"7.", None))
        self.mission_8.setText(QCoreApplication.translate("strength_assignment", u"8.", None))
        self.mission_9.setText(QCoreApplication.translate("strength_assignment", u"9.", None))
        self.mission_10.setText(QCoreApplication.translate("strength_assignment", u"10.", None))
        self.minus5.setText("")
        self.plus5.setText("")
        self.minus4.setText("")
        self.plus4.setText("")
        self.minus3.setText("")
        self.plus3.setText("")
        self.plus2.setText("")
        self.minus2.setText("")
        self.plus1.setText("")
        self.minus1.setText("")
        self.mission1_show.setText(QCoreApplication.translate("strength_assignment", u"\u793e\u56e2\u6d3b\u52a8  1000", None))
        self.mission2_show.setText(QCoreApplication.translate("strength_assignment", u"\u793e\u56e2\u6d3b\u52a8  1000", None))
        self.mission3_show.setText(QCoreApplication.translate("strength_assignment", u"\u793e\u56e2\u6d3b\u52a8  1000", None))
        self.mission4_show.setText(QCoreApplication.translate("strength_assignment", u"\u793e\u56e2\u6d3b\u52a8  1000", None))
        self.mission5_show.setText(QCoreApplication.translate("strength_assignment", u"\u793e\u56e2\u6d3b\u52a8  1000", None))
        self.left_button.setText("")
        self.right_button.setText("")
        self.total_strength.setText(QCoreApplication.translate("strength_assignment", u"100", None))
        self.label_14.setText(QCoreApplication.translate("strength_assignment", u"10000", None))
        self.shifo_label.setText(QCoreApplication.translate("strength_assignment", u"\u5b66\u6821\u5c06\u4e3e\u529e\u8fce\u65b0\u665a\u4f1a\uff0c\u4f60\u662f\u5426\u9009\u62e9\u53c2\u52a0\uff1f", None))
        self.true_button.setText(QCoreApplication.translate("strength_assignment", u"\u662f", None))
        self.false_button.setText(QCoreApplication.translate("strength_assignment", u"\u5426", None))
    # retranslateUi

